document.writeln(" <footer>");
document.writeln("        <div class=\'footer_text_left\'>");
document.writeln("            <div class=\'container\'>");
document.writeln("                <div class=\'row footer-row-style\'>");
document.writeln("                    <div class=\'col-4\'>");
document.writeln("                        <p style=\'text-align: left;\'>");
document.writeln("                            <a href=\'./3.0_charge.html\'>");
document.writeln("                                <span style=\'font-size: medium;color: rgba(255, 255, 255 ,0.96)\'>費用說明</span>");
document.writeln("                            </a>");
document.writeln("                        </p>");
document.writeln("                        <p style=\'text-align: left \'>");
document.writeln("                            <a href=\'./11.0_register.html\'>");
document.writeln("                                <span style=\'font-size: medium;color: rgba(255, 255, 255 ,0.96)\'>立即申請</span>");
document.writeln("                            </a>");
document.writeln("                        </p>");
document.writeln("                        <p style=\'text-align: left \'>");
document.writeln("                            <a href=\'/sparklr2/login.jsp\'>");
document.writeln("                                <span style=\'font-size: medium;color: rgba(255, 255, 255 ,0.96)\'>會員專區</span>");
document.writeln("                            </a>");
document.writeln("                        </p>");
document.writeln("                        <p style=\'text-align: left \'>");
document.writeln("                            <a href=\'5.0_activity.html\'>");
document.writeln("                                <span style=\'font-size: medium;color: rgba(255, 255, 255 ,0.96)\'>活動報名</span>");
document.writeln("                            </a>");
document.writeln("                        </p>");
document.writeln("                        <p style=\'text-align: left \'>");
document.writeln("                            <a href=\'./6.0_process.html\'>");
document.writeln("                                <span style=\'font-size: medium;color: rgba(255, 255, 255 ,0.96)\'>輔導流程</span>");
document.writeln("                            </a>");
document.writeln("                        <p style=\'text-align: left \'>");
document.writeln("                            <a href=\'https://www.mitac.com.tw/\'>");
document.writeln("                                <span style=\'font-size: medium;color: rgba(255, 255, 255 ,0.96)\'>關於神通</span>");
document.writeln("                            </a>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'col-4\'>");
document.writeln("                        <p style=\'text-align: left \'>");
document.writeln("                            <a href=\'./7.0_faq.html\'>");
document.writeln("                                <span style=\'font-size: medium;color: rgba(255, 255, 255 ,0.96)\'>常見問答</span>");
document.writeln("                            </a>");
document.writeln("                        </p>");
document.writeln("                        <p style=\'text-align: left \'>");
document.writeln("                            <a href=\'./9.0_related.html\'>");
document.writeln("                                <span style=\'font-size: medium;color: rgba(255, 255, 255 ,0.96)\'>相關連結</span>");
document.writeln("                            </a>");
document.writeln("                        </p>");
document.writeln("                        <p style=\'text-align: left \'>");
document.writeln("                            <a href=\'./4.0_case.html\'>");
document.writeln("                                <span style=\'font-size: medium;color: rgba(255, 255, 255 ,0.96)\'>成功案例</span>");
document.writeln("                            </a>");
document.writeln("                        </p>");
document.writeln("                        <p style=\'text-align: left \'>");
document.writeln("                            <a href=\'https://www.facebook.com/mitacinv/\'  target=\'框架名稱\'>");
document.writeln("                                <span style=\'font-size: medium;color: rgba(255, 255, 255 ,0.96)\'>粉絲專頁</span>");
document.writeln("                            </a>");
document.writeln("                        </p>");
document.writeln("                        <p style=\'text-align: left \'>");
document.writeln("                            <a href=\'/tw/law.html' >");
document.writeln("                                <span style=\'font-size: medium;color: rgba(255, 255, 255 ,0.96)\'>服務條款</span>");
document.writeln("                            </a>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'col-4\'>");
document.writeln("                        <p style=\'text-align: left \'>");
document.writeln("                            <a href=\'/tw/contact_us.html' \'>");
document.writeln("                                <span style=\'font-size: medium;color: rgba(255, 255, 255 ,0.96)\'>聯絡我們</span>");
document.writeln("                            </a>");
document.writeln("                        </p>");
document.writeln("                        <p>");
document.writeln("                            <span style=\'font-size: 15px; \'>");
document.writeln("                                <span style=\'background-color: color:#ffffff; \'>神通資訊股份有限公司</span>");
document.writeln("                            </span>");
document.writeln("                        </p>");
document.writeln("                        <p>");
document.writeln("                            <span style=\'color: #ffffff; font-family: inherit; font-size:15px; \'>內湖企業總部</span>");
document.writeln("                        </p>");
document.writeln("                        <p>");
document.writeln("                            <span style=\'color: #ffffff; font-family: inherit; font-size:15px; \'>114台北市內湖區堤頂大道二段187號");
document.writeln("                            </span>");
document.writeln("                        </p>");
document.writeln("                        <p>");
document.writeln("                            <span style=\'color: #ffffff; font-family: inherit; font-size:15px; \'>TEL:886-2-26576666</span>");
document.writeln("                        </p>");
document.writeln("                        <p>");
document.writeln("                            <span style=\'color: #ffffff; font-family: inherit; font-size:15px; \'>FAX:886-2-26576668</span>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </footer>");